export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";

export const SET_CLICKED = "SET_CLICKED";

export const SET_FAVORITES = "SET_FAVORITES";
