export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";

export const SET_CLICKED = "SET_CLICKED";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SAVE_FAVS_START = "SAVE_FAVS_START";
export const SAVE_FAVS_SUCCESS = "SAVE_FAVS_SUCCESS";
export const SAVE_FAVS_FAIL = "SAVE_FAVS_FAIL";
